run:
  # Our CI expects a vendor directory, hence we have to use -mod=readonly here as well.
  modules-download-mode: readonly

issues:
  # on default, golangci-lint excludes gosec. Hence, we have to
  # explicitly disable the exclude-use-default: https://github.com/golangci/golangci-lint/issues/1504
  exclude-use-default: false

# individual linter configs go here
linters-settings:

# default linters are enabled `golangci-lint help linters`
linters:
  disable-all: true
  enable:
  - asciicheck
  - bidichk
  - containedctx
  - decorder
  - dogsled
  - dupl
 #- forbidigo # we use prints and stuff as this is a dev project
  - forcetypeassert
  - funlen
  - gci
 #- gochecknoglobals # we use globals for cobra commands init
 #- gochecknoinits # we use init to fill in the cobra commands
  - gocognit
  - goconst
  - gocyclo
  - godot
  - godox
  - gofmt
  - gofumpt
  - goheader
  - goimports
  - gomnd
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - gosec
  - grouper
  - ifshort
  - lll
  - maintidx
  - misspell
  - nakedret
  - nestif
  - nlreturn
  - nolintlint
  - paralleltest
  - prealloc
  - predeclared
  - promlinter
  - tagliatelle
  - testpackage
  - whitespace
  - wsl
