# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
    - which syft

env:
  # to allow github to override it if I need to 
  - GITHUB_REPOSITORY_OWNER={{ if index .Env "GITHUB_REPOSITORY_OWNER"  }}{{ .Env.GITHUB_REPOSITORY_OWNER }}{{ else }}georgettica{{ end }}

builds:
  - env:
      - CGO_ENABLED=0
      - GOFLAGS=-mod=readonly -trimpath
    ldflags:
      - "-extldflags=-znow"
      - "-extldflags=-zrelro"
      - "-s"
      - "-w"
    goos:
      - darwin
      - linux
      - windows

dockers:
  - image_templates:
    - ghcr.io/{{.Env.GITHUB_REPOSITORY_OWNER}}/{{ .ProjectName }}:latest
    - ghcr.io/{{.Env.GITHUB_REPOSITORY_OWNER}}/{{ .ProjectName }}:{{ .Version }}
    ids:
      - pagerduty-tekton-interceptor
    dockerfile: ./hack/Dockerfile.goreleaser

archives:
  - replacements:
      386: i386
      amd64: x86_64
      darwin: Darwin
      linux: Linux
      windows: Windows

checksum:
  name_template: 'checksums.txt'

sboms:
  - artifacts: archive
  - id: source
    artifacts: source 

signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    env:
      - COSIGN_EXPERIMENTAL=1
    args: 
      - sign-blob
      - "--oidc-issuer=https://token.actions.githubusercontent.com"
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"
    artifacts: all

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Documentation'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999
