apiVersion: v1
kind: Service
metadata:
  name: pagerduty-webhook-interceptor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pagerduty-webhook-interceptor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
